/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.rbda.gui;

import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import org.rbda.pipeline.Pipeseg;

/**
 *
 * @author kewin
 */
public class MechanicalFault extends javax.swing.JFrame  implements ItemListener{
    
    public double B1,B2,B3,B4,B5,B6,B7,B8,B9,B10,B11,B12;
    public double E1,E2,E3,E4,E5,E6,E7,E8,E9,E10,E11;
    public Pipeseg pipeseg;

    /**
     * Creates new form MechanicalFault
     */
    public MechanicalFault() {
        initComponents();
        jComboBox1.addItemListener(this);
        jComboBox2.addItemListener(this);
        jComboBox3.addItemListener(this);
        jComboBox4.addItemListener(this);
        jComboBox5.addItemListener(this);
        jComboBox6.addItemListener(this);
        jComboBox7.addItemListener(this);
        jComboBox8.addItemListener(this);
        jComboBox9.addItemListener(this);
        jComboBox10.addItemListener(this);
        jComboBox11.addItemListener(this);
        jComboBox12.addItemListener(this);
    }
    //该构造函数关联管段，可以将计算结果赋给管段中的pipeseg.protection_factor作为碰撞概率  
    public MechanicalFault(Pipeseg pipeseg) {
        initComponents();
        jComboBox1.addItemListener(this);
        jComboBox2.addItemListener(this);
        jComboBox3.addItemListener(this);
        jComboBox4.addItemListener(this);
        jComboBox5.addItemListener(this);
        jComboBox6.addItemListener(this);
        jComboBox7.addItemListener(this);
        jComboBox8.addItemListener(this);
        jComboBox9.addItemListener(this);
        jComboBox10.addItemListener(this);
        jComboBox11.addItemListener(this);
        jComboBox12.addItemListener(this);
   
        this.pipeseg = pipeseg;
    }
    
    @Override
    public void itemStateChanged(ItemEvent e) {
        
        if(e.getStateChange() == ItemEvent.SELECTED){
               getcomboboxvalue();
               faulttreevalue(); 
            }             
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jComboBox7 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jComboBox8 = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jComboBox9 = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jComboBox10 = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jComboBox11 = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jComboBox12 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("确定");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("取消");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel13.setText("碰撞概率：");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(40, 40, 40)
                .addComponent(jButton2)
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jLabel13)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setLayout(new java.awt.GridLayout(12, 2));

        jLabel1.setText("在管线上方开挖");
        jPanel2.add(jLabel1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "一级地区(/ km·年 )", "二级地区(/ km·年 )", "三级地区(/ km·年 )", "四级地区(/ km·年 )" }));
        jPanel2.add(jComboBox1);

        jLabel2.setText("第三方不知道有管线");
        jPanel2.add(jLabel2);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "直接向联系人寄发广告" }));
        jPanel2.add(jComboBox2);

        jLabel3.setText("未发现管线地面标志");
        jPanel2.add(jLabel3);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "有选择地在交叉点设立标志 ", "在所有交叉点设立标志 ", "在所有交叉点并在管道沿线按一定间隔设立标志 " }));
        jPanel2.add(jComboBox3);

        jLabel4.setText("未发现管线埋地标志");
        jPanel2.add(jLabel4);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "无埋地标志", "有埋地标志" }));
        jPanel2.add(jComboBox4);

        jLabel5.setText("第三方选择不予通告 ");
        jPanel2.add(jLabel5);

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "自愿", "强制但无强制措施", "强制加民事处罚 ", "签订管道用地协议" }));
        jPanel2.add(jComboBox5);

        jLabel6.setText("第三方未能避开管道 ");
        jPanel2.add(jLabel6);

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "不适用" }));
        jPanel2.add(jComboBox6);

        jLabel7.setText("巡线人员未发现第三方开挖活动");
        jPanel2.add(jLabel7);

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "每半日巡查 ", "每日巡查 ", "隔日巡查 ", "每周巡查 ", "隔周巡查 ", "每月巡查 ", "每半年巡查 ", "每年巡查" }));
        jPanel2.add(jComboBox7);

        jLabel8.setText("其它人员未报告第三方开挖活动");
        jPanel2.add(jLabel8);

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "不适用" }));
        jPanel2.add(jComboBox8);

        jLabel9.setText("第三方在管线部门回应前开挖");
        jPanel2.add(jLabel9);

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "当日内作出回应 ", "两日内作出回应" }));
        jPanel2.add(jComboBox9);

        jLabel10.setText("临时标志不正确");
        jPanel2.add(jLabel10);

        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "按公司资料 ", "管道探测仪", "人工开挖" }));
        jPanel2.add(jComboBox10);

        jLabel11.setText("与标记正确的管道发生意外碰撞");
        jPanel2.add(jLabel11);

        jComboBox11.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "提供管道线路资料 ", "定位 / 标记 ", "定位 / 标记 / 现场监督 ", "由管线部门开挖" }));
        jPanel2.add(jComboBox11);

        jLabel12.setText("开挖深度超过管线埋深");
        jPanel2.add(jLabel12);

        jComboBox12.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "管道埋深 0.8 m ", "管道埋深1.0 m", "管道埋深1.2 m", "管道埋深1.5 m", "管道埋深1.8 m" }));
        jPanel2.add(jComboBox12);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:        
        getcomboboxvalue();
        faulttreevalue();
        //System.out.println(E11);
        pipeseg.protection_factor =  E11;
        this.dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    public void getcomboboxvalue(){        
        switch(jComboBox1.getSelectedIndex()){
            case 0:
                B1= 0.06;
                break;
            case 1:
                B1=0.2;
                break;
            case 2:
                B1=0.33;
                break;
            case  3:
                B1 = 0.25;
                break;
            default:
                B1 = 0.06;
                break;
        }
        switch(jComboBox2.getSelectedIndex()){
            case 0:
                B2= 0.09;
                break;
            default:
                B2= 0.09;
                break;
        }
        switch(jComboBox3.getSelectedIndex()){
            case 0:
                B3= 0.37;
                break;
            case 1:
                B3= 0.18;
                break;
            case 2:
                B3= 0.10;
                break;
            default:
                B3= 0.37;
                break;
        }
        switch(jComboBox4.getSelectedIndex()){
            case 0:
                B4= 1.0;
                break;
            case 1:
                B4=0.1;
                break;
            default:
                B4= 1.0;
                break;
        }
        switch(jComboBox5.getSelectedIndex()){
            case 0:
                B5= 0.65;
                break;
            case 1:
                B5=0.27;
                break;
            case 2:
                B5=0.09;
                break;
            case  3:
                B5 =0.09;
                break;
            default:
                B5= 0.65;
                break;
        }

        switch(jComboBox6.getSelectedIndex()){
            case 0:
                B6= 0.4;
                break;
            default:
                B6= 0.4;
                break;
        }
        switch(jComboBox7.getSelectedIndex()){
            case 0:
                B7= 0.08;
                break;
            case 1:
                B7=0.21;
                break;
            case 2:
                B7=0.44;
                break;
            case  3:
                B7 = 0.78;
                break;
            case  4:
                B7 = 0.89;
                break;
            case  5:
                B7 = 0.96;
                break;
            case  6:
                B7 = 0.99;
                break;
            case  7:
                B7 = 0.997;
                break;
            default:
                B7 = 0.08;
                break;
        }

        switch(jComboBox8.getSelectedIndex()){
            case 0:
                B8= 0.85;
                break;
            default:
                B8 = 0.85;
                break;
        }
        switch(jComboBox9.getSelectedIndex()){
            case 0:
                B9= 0.1;
                break;
            case 1:
                B9=0.54;
                break;
            default:
                B9= 0.1;
                break;
        }

        switch(jComboBox10.getSelectedIndex()){
            case 0:
                B10= 0.24 ;
                break;
            case 1:
                B10=0.06;
                break;
            case 2:
                B10=0.01 ;
                break;
            default:
                B10= 0.24 ;
                break;
        } 

        switch(jComboBox11.getSelectedIndex()){
            case 0:
                B11=0.27;
                break;
            case 1:
                B11=0.17;
                break;
            case 2:
                B11=0.11;
                break;
            case  3:
                B11 =0.11;
                break;
            default:
                B11 =0.11;
                break;
        } 
        
        switch(jComboBox12.getSelectedIndex()){
            case 0:
                B12= 0.80;
                break;
            case 1:
                B12=0.65;
                break;
            case 2:
                B12=0.50;
                break;
            case  3:
                B12 = 0.20;
                break;
            case  4:
                B12 = 0.10;
                break;
            default:
                B12 = 0.80;
                break;
        }
        
    }
    
    public void faulttreevalue(){        
        //选定各项的措施后，按照事故树计算
        E1 = B2*B3*B4;
        E2 = B5*B6;
        E3 = 1- (1-E1)*(1-E2);
        E4 = E3*B7*B8;
        E5 = B6*B9;
        E6 = B6*B10;
        E7 = 1- (1-E5)*(1-E6);
        E8 = B4*E7;
        E9 = 1- (1-E4)*(1-E8);
        E10= 1- (1-E9)*(1-B11);
        E11= B1*E10*B12;
        jTextField1.setText(String.valueOf(E11));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MechanicalFault.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MechanicalFault.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MechanicalFault.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MechanicalFault.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MechanicalFault().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox10;
    private javax.swing.JComboBox jComboBox11;
    private javax.swing.JComboBox jComboBox12;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JComboBox jComboBox7;
    private javax.swing.JComboBox jComboBox8;
    private javax.swing.JComboBox jComboBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
