/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.rbda.gui;

import java.awt.GridLayout;
import java.util.Iterator;
import javax.swing.JLabel;
import org.rbda.auxclasses.NewDistrButton;
import org.rbda.pipeline.Pipeseg;

/**
 *
 * @author kewin
 */
public class PipesegPropertyAddPanel extends javax.swing.JPanel {
    
    public Pipeseg pipeseg;
    
    public PipesegPropertyAddPanel(Pipeseg pipeseg){
        initComponents();
        this.pipeseg = pipeseg;
        Panel_Init();
    }

    /**
     * Creates new form PipesegPropertyAddPanel
     */
    public PipesegPropertyAddPanel() {
        initComponents();
    }
    
    public void Panel_Init(){
        setLayout(new GridLayout(pipeseg.parameters_needed.size(),2));
        
        NewDistrButton[] distribution_button = new NewDistrButton[pipeseg.parameters_needed.size()];

        Iterator iter = pipeseg.parameters_needed.keySet().iterator();
        String para_name;
        int i = 0;
        while(iter.hasNext()){
            para_name = (String)iter.next();
            distribution_button[i]=new NewDistrButton(para_name, pipeseg);
            add(new JLabel(para_name));
            add(distribution_button[i]); 
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
