/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.rbda.auxclasses;

import java.util.Iterator;
import java.util.Scanner;
import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreeModel;
import javax.swing.tree.TreeSelectionModel;
import org.rbda.gui.MainFrame;
import org.rbda.pipeline.Pipeline;
import org.rbda.pipeline.Pipeseg;

/**
 *
 * @author kewin
 */
public class ProjectTreePanel extends javax.swing.JPanel {
    Pipeline pipeline;
    MainFrame mainframe;
    public TreeModel treemodel;
    public DefaultMutableTreeNode root;

    /**
     * Creates new form ProjectTreePanel
     */
    public ProjectTreePanel(Pipeline pipeline, MainFrame mainframe) {
        this.mainframe = mainframe;
        this.pipeline = pipeline;
        initComponents();
        jTree1.addMouseListener(new ProjectTreeSelectionListener( this.mainframe));
        Clear_tree();
    }
    
    public JTree get_jTree(){
        return jTree1;
    }
    
    public void Set_Dimension(int Width, int Height){
        jTree1.setSize(Width, Height);
        jScrollPane1.setSize(Width, Height);
    }
    public void Clear_tree(){
        jTree1.setModel(null);
    }
 
     
     
     
    public void Update_tree(){
        root = new  DefaultMutableTreeNode(pipeline.getName());       
        if (pipeline.pipesegs !=null){
            for (Pipeseg pipesegs: pipeline.pipesegs){
                DefaultMutableTreeNode data = new  DefaultMutableTreeNode(pipesegs.name);
                root.add(data);
            }
        }
        treemodel = new DefaultTreeModel(root);
        jTree1.setModel(treemodel);
        jTree1.setEditable(true);
        jTree1.setShowsRootHandles(true);
        jTree1.getSelectionModel().setSelectionMode(TreeSelectionModel.SINGLE_TREE_SELECTION);
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();

        jTree1.setPreferredSize(new java.awt.Dimension(100, 150));
        jScrollPane1.setViewportView(jTree1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
}
